### PR TITLE
remove warning about unable to check for latest version

### LINKED ISSUE #1170: Maven settings prevent checking for later versions of selected libraries
This error message when creating a new maven project and adding libraries is surprising. It sounds like even if this fails maybe we shouldn't bother the user with this?

image

### PR DESCRIPTION
**Pull request by elharo**
fix #1170 @akerekes

### CODE REVIEW

**Comment by briandealwis** [comment]
That was deliberately introduced as #1044 (and I've been bitten by this myself). Rather than backing it out entirely, can't we change `WARNING` to `INFO` and fix-up the wording?

**Comment by elharo** [comment]
The question is whether anybody actually expects this to happen or is this just a best effort behind the scenes thing. Rajeev and I were both independently confused by this when we hit it. 

If we change it to info, what wording do you suggest?

I think not being able to check for the latest version is the default setting in Eclipse since neither Rajeev nor myself made the effort to change it. Is it likely this feature will work for most users out of the box?

**Comment by briandealwis** [comment]
That you see the text means you will be affected by the issue (I think the original issue is #830). This issue is perhaps too subtle to explain in a single sentence, especially to provide instructions on how to fix it. Perhaps we should have a separate wizard page that can provide more detail — with an option for temporarily disabling the setting?

**Comment by elharo** [comment]
I think (not yet sure) that a default install of Eclipse+m2e is going to hit this every time. 

I think a separate wizard page is overly complex.

What's the impact on the user of simply not resolving the problem and allowing them to proceed with their potentially older version of the library?

**Comment by akerekes** [comment]
@elharo they can end up with a rather old library and if they want to update it, they will have to do it manually:
- remove the old one we've added to the project
- download and add the newer version to the project

**Comment by elharo** [comment]
Yes,  but this warning doesn't prevent the problem or give guidance on how to fix it.

**Comment by elharo** [comment]
Ping. I'm going to keep pushing on this one. We have now had *3* engineers who all said WTF when they saw this message. That's strong evidence this warning is confusing. And this happens with the default set of preferences. I do not want to show a warning to every developer who creates a maven-based project, and right now that's what we're doing.

**Comment by elharo** [comment]
Let's talk about #1223 next week. I'm not sure how high a priority it is. Independently of that , though, we do need to fix this issue, and we can do it now.

**Pull request merged**
