### PR TITLE
Include plugin.xml in .cte13 bundle

### PR DESCRIPTION
**Pull request by chanseokoh**
BTW, we should remove `.appengine` from the bundle name.

### CODE REVIEW

**Comment by briandealwis** [comment]
oh jeepers

**Comment by chanseokoh** [comment]
Probably adding `PluginXmlTest` can catch this.

**Comment by elharo** [comment]
I was just thinking that. I wonder if there's a way to write such a test that tests all our bundles?

**Comment by briandealwis** [comment]
I initially put the updater into `.compat`, but it required some significant refactoring as we have `.appengine.facets` depend ending on `.compat` to pull in `GpeMigrator`, etc., so I backed it out and went for this simpler solution.

I'll push up the refactoring, but it can wait for 1.4.

**Comment by briandealwis** [comment]
Refactoring in #2517

**Pull request merged**
