### PR TITLE
Mark MiniSelector Combo as vertical=SWT.FILL

### LINKED ISSUE #2424: Project MiniSelector height is initially small
I thought it could be a problem only on my Ubuntu, but today, I noticed that it also happens on Fedora. The combo restores it's proper size when I resize the dialog.

screenshot from 2017-09-26 14 37 42

### PR DESCRIPTION
**Pull request by briandealwis**
Fixes #2424 I hope: it doesn't seem to make a difference on MacOS

### CODE REVIEW

**Comment by chanseokoh** [comment]
Doesn't work, unfortunately. Maybe someone with Linux should work on it.

**Comment by briandealwis** [comment]
I tried with gtk 2.24.25 and it looks "fine":

screen shot 2017-09-28 at 2 54 14 pm

**Comment by chanseokoh** [comment]
It's fine with or without this change?

**Comment by chanseokoh** [comment]
Also try to select some projects, because on my Ubuntu, it's hard to see if the height is not enough until you see characters in it: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2424#issuecomment-332938375.

**Comment by briandealwis** [comment]
That was running from source without the patch.  I'll install Ubuntu and see what happens.

**Comment by chanseokoh** [comment]
#2424 closed. Do you want to make this change anyway?

**Comment by briandealwis** [comment]
I hadn't applied this change!  I was just running from `master`.

**Comment by chanseokoh** [comment]
That's what I am saying. Close it then?

**Comment by briandealwis** [comment]
Oops — I thought I had closed it.

**Pull request closed without merging**
