### PR TITLE
Fix release version

### PR DESCRIPTION
**Pull request by chanseokoh**

### CODE REVIEW

**Comment by briandealwis** [comment]
Hmm, the category still isn't appearing.  Investigating.

**Comment by elharo** [comment]
Where/what exactly are you not seeing? 

image

image

**Comment by chanseokoh** [comment]
@briandealwis try re-installing. I see 1.2.0.

**Comment by briandealwis** [comment]
Huh, in my local build, the category IU isn't copied across into the target repository.  That is:
```
$ unzip -p gcp-repo/target/repository/content.jar | grep "<unit.*id='com.google.cloud.tools.eclipse.category'"
```
is empty **unless** I change the `requires.1.range` to a tight bound.

I don't know why it's working in the main builds.

Anyways, I have a patch that will pull the version from the pom.xml so that we don't have to modify the p2.inf for future releases.

**Comment by briandealwis** [comment]
Ah, it works in the release build as `release/release_after_kokoro.sh` re-publishes the signed features and bundles, and then re-publishes the `metadata.product` (which pulls in the `metadata.p2.inf`).

**Comment by elharo** [comment]
So, no need to hold this release, right?

**Comment by briandealwis** [comment]
Good to go 👍

**Pull request merged**
