### PR TITLE
Install Spring Boot deps before tests; move to 1.5.6-RELEASE

### PR DESCRIPTION
**Pull request by briandealwis**
Cause Spring Boot dependencies to be downloaded to the local Maven repository by the build-time Maven instance rather than M2Eclipse at test time.  The hope is that this will avoid any repository corruption as tracked in #2284.

This change updates the two Spring Boot test projects to be consistent and use 1.5.6-RELEASE.

### CODE REVIEW

**Comment by briandealwis** [comment]
Failure due to #2378.  Will merge with HEAD (with fix from #2672).

**Comment by chanseokoh** [comment]
Looking at [this Kokoro log](https://pantheon.corp.google.com/logs/viewer?project=cloud-tools-for-eclipse-kokoro&minLogLevel=0&expandAll=false&timestamp=2017-12-13T23:16:12.983607262Z&advancedFilter=resource.type%3D%22project%22%0Aresource.labels.project_id%3D%22cloud-tools-for-eclipse-kokoro%22%0AlogName%3D%22projects%2Fcloud-tools-for-eclipse-kokoro%2Flogs%2Fkokoro-google-cloud-eclipse-gcp_windows-presubmit-2-20171213-144028%22&dateRangeStart=2017-12-13T22:36:38.741Z&dateRangeEnd=2017-12-13T23:36:38.741Z&interval=PT1H) from #2682 which failed, seems like a lot of dependencies are still missing.

Maybe we should try simplifying the zip test projects. For example,
- Ditch `springboot-appengine-standard.zip` and replace it with a non-Spring project. `ImportMavenAppEngineStandardProjectTest.runImport()` is the only consumer of the zip, which doesn't have to be Spring-specific.
- There might be some way to minimize `web-fragment-example.zip` or `spring-boot-test.zip` too.

**Comment by chanseokoh** [comment]
`org.springframework:spring-web:jar:4.3.10.RELEASE` from `web-fragment-example.zip` is subsumed by `org.springframework.boot:spring-boot-starter-web:1.5.6.RELEASE`, so no need to update that.

**Comment by elharo** [comment]
Simplifying the zip test projects sounds like a very good idea.

**Pull request merged**
