### PR TITLE
Update deployment properties page on facet change

### PR DESCRIPTION
**Pull request by nbashirbello**
Show an error message on the deployment properties page when it shows standard deployment information but the standard facet has been uninstalled. Same for flex. 
Fix for #783

### CODE REVIEW

**Comment by nbashirbello** [comment]
@briandealwis

**Comment by chanseokoh** [comment]
I tried to do a manual testing, and looks like it breaks validation in the preferences page. For example, if you check `Override generated version`, it doesn't show the error message on top. When a user tried to move to another preference page, it's blocked with the following error:

selection_002

**Comment by nbashirbello** [comment]
@elharo 

When you saw the "Could not accept changes" message, had you set a value for "Bucket". It looks like if "Override default Cloud Storage bucket for staging" is checked, you have to have an input for "Bucket". (The "Apply" button also gets disabled when this happens).

**Comment by elharo** [comment]
I think @chanseokoh saw that message, not me.

**Comment by chanseokoh** [comment]
Explained the error to @nbashirbello offline.

**Comment by nbashirbello** [comment]
Not ready for review!

**Comment by nbashirbello** [comment]
PR ready for review :)

**Pull request merged**
