### PR TITLE
update apache commons compression

### PR DESCRIPTION
**Pull request by elharo**
@briandealwis This is the version that will be used by the next release of appengine-plugins-common

### CODE REVIEW

**Comment by elharo** [comment]
typical flake:

```

3881 [WARNING] Error injecting: org.eclipse.tycho.p2.resolver.P2DependencyResolver

com.google.inject.ProvisionException: Unable to provision, see the following errors:



1) Error notifying InjectionListener org.eclipse.sisu.plexus.PlexusBeanBinder@26722665 of org.eclipse.tycho.p2.resolver.P2DependencyResolver.

 Reason: java.lang.RuntimeException: java.lang.IllegalStateException: Service is not registered class='interface org.eclipse.tycho.core.shared.ProxyServiceFacade'

  while locating org.eclipse.tycho.p2.resolver.P2DependencyResolver
```

**Comment by elharo** [comment]
we're seeing a lot of flaky tycho injection failures that look like this:

```
1) Error notifying InjectionListener org.eclipse.sisu.plexus.PlexusBeanBinder@26722665 of org.eclipse.tycho.p2.resolver.P2DependencyResolver.

 Reason: java.lang.RuntimeException: java.lang.IllegalStateException: Service is not registered class='interface org.eclipse.tycho.core.shared.ProxyServiceFacade'

  while locating org.eclipse.tycho.p2.resolver.P2DependencyResolver

  at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.3.0, parent: java.net.URLClassLoader@5caf905d] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)

  while locating org.eclipse.tycho.core.DependencyResolver annotated with @com.google.inject.name.Named(value=p2)



1 error

      role: org.eclipse.tycho.core.DependencyResolver

  roleHint: p2

	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)

	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)

	at org.eclipse.tycho.core.resolver.DefaultDependencyResolverFactory.lookupDependencyResolver(DefaultDependencyResolverFactory.java:74)

	... 23 more

Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:
```

Maybe a race condition?

**Comment by elharo** [comment]
I'm wondering if the photon failure isn't a flake:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=494913

**Comment by briandealwis** [comment]
Could you try tweaking the .travis.yml to use a later Maven?  I tried tweaking the `.travis.yml` to remove the `-Pjacoco` and the rebuild was fine.
```diff
--- .travis.yml
+++ .travis.yml
@@ -9,7 +9,7 @@ before_install:
   - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
 install: 
   # use mvn ≥ 3.3.9 to ensure faulty test exit states fail the build (#1276)
-  - mvn -B -N io.takari:maven:wrapper -Dmaven=3.5.0
+  - mvn -B -N io.takari:maven:wrapper -Dmaven=3.5.4
   # download and install Cloud SDK (may be cached)
   - build/install-cloudsdk.sh 241.0.0 $HOME
 # ECLIPSE_TARGET is the targeted platform: photon is the default target
```

**Comment by briandealwis** [comment]
@googlebot I consent

**Pull request merged**
