### PR TITLE
Prepare release 1.8.1

### PR DESCRIPTION
**Pull request by chanseokoh**

### CODE REVIEW

**Comment by briandealwis** [comment]
I wonder why this only just started failing.

```
testObjectify6LibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.152 s  <<< FAILURE!

java.lang.AssertionError: 
Expected: is "20.0"
     but: was "27.1-android"
	at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testObjectify6LibraryConfig(CloudLibrariesInPluginXmlTest.java:243)

testObjectify5LibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.002 s  <<< FAILURE!

java.lang.AssertionError: expected:<6.0.3> but was:<6.0.4>
	at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testObjectify5LibraryConfig(CloudLibrariesInPluginXmlTest.java:170)
```

**Comment by elharo** [comment]
I bet 6.0.4 was released and we have a test that checks which version is actually puklled in.

**Comment by briandealwis** [comment]
Maybe, but `testObjectify5LibraryConfig` shouldn't be pulling 6.x, should it?

**Comment by briandealwis** [comment]
just fixing this

**Comment by elharo** [comment]
Yes, it should. We never pull 5 now.

**Comment by briandealwis** [comment]
Ah right — I'll rename the test method too.

**Pull request merged**
