### PR TITLE
Export classes for dataflow

### PR DESCRIPTION
**Pull request by chanseokoh**
For me, I have to export these classes to get rid of any compilation error.

### CODE REVIEW

**Comment by chanseokoh** [comment]
Ah, it was just that I haven't merged #1789. I just added "x-friends", as the proxy package is only for the `.dataflow.ui` bundle.

**Comment by briandealwis** [comment]
Should we do the `x-friends` through a general sweep?

**Comment by chanseokoh** [comment]
Maybe viable with a limited scope, but to me, it seems not worth putting much time to it. I don't really care much about `x-friends`.

**Comment by elharo** [comment]
I'm not sure why you seem to need this and I don't.

**Comment by chanseokoh** [comment]
Yeah, I don't need to be bothered. Closing.

**Pull request closed without merging**
