### PR TITLE
Show vertical scrollbar when necessary

### LINKED ISSUE #2640: Change the section title of the Google Cloud Platform Libraries
Currently, the section title says Google Cloud Platform Libraries. But the official name per the branding guidelines is Cloud Client Libraries for Java.

screen

### PR DESCRIPTION
**Pull request by chanseokoh**
For #2641.

add library _014

add library _013

### CODE REVIEW

**Comment by chanseokoh** [comment]
Oh, wait. I just noticed the label is in sync with the wizard page subtitle.

**Comment by chanseokoh** [comment]
Alright, backing off #2640. Let's fix only #2641 in this PR.

**Comment by briandealwis** [comment]
This multi-column contents was just a stop-gap.  I think we should rototill the actual dialog contents to be a master/detail-like approach as in CT4IJ.

**Comment by elharo** [comment]
rototill?

**Comment by chanseokoh** [comment]
Let me quickly see if I can show a scrollbar for each column (when necessary).

**Comment by chanseokoh** [comment]
Pushing up what I've gotten so far.

**Pull request merged**
