### PR TITLE
Update target platform definitions

### LINKED ISSUE #3255: Builds failing due to linuxtools.docker.feature
Time to update the target platform definition again?

```
14199 [INFO] Fetching content.jar from http://download.eclipse.org/linuxtools/update-docker/ (58.42kB)
14201 [INFO] Fetching content.jar from http://download.eclipse.org/linuxtools/update-docker/ (58.42kB)
14362 [ERROR] Failed to resolve target definition /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/eclipse/photon/gcp-eclipse-photon.target: Could not find "org.eclipse.linuxtools.docker.feature.feature.group/4.0.0.201806122135" in the repositories of the current location -> [Help 1]
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #3255.

### CODE REVIEW

**Comment by chanseokoh** [comment]
Hmm... I feel like there's something more to this.

**Comment by chanseokoh** [comment]
The Java 11 build is always terminating. It looks like it's generating too many log lines:

```
!ENTRY org.eclipse.wst.sse.core 1 1 2018-09-21 14:13:05.290

!MESSAGE Indexing project test0.46651436989567885 for

The job exceeded the maximum log length, and has been terminated.
```

```
3.9.2.v201803040536.jar,/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.wst.dtd.core/1.2.0.v201802171654/org.eclipse.wst.dtd.core-1.2.0.v201802171654.jar,/home/travis/.m2/repository/p2/osgi/bundle/org.eclipse.ws

The job exceeded the maximum log length, and has been terminated.
```

The Photon build seems to fail too (also in the other PR #3254).

@briandealwis could you look into these?

**Comment by briandealwis** [comment]
The Oxygen (4.8) builds are failing for different reasons:
```
testNoJstl12JarIfMavenProject(com.google.cloud.tools.eclipse.appengine.newproject.flex.CreateAppEngineFlexWtpProjectTest)  Time elapsed: 24.433 sec  <<< ERROR!

org.eclipse.m2e.core.internal.project.registry.StaleMutableProjectRegistryException
```

vs 

```
testStage_springBoot(com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest)  Time elapsed: 6.172 sec  <<< ERROR!
org.eclipse.core.runtime.OperationCanceledException
	at com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest.testStage_springBoot(FlexMavenPackagedProjectStagingDelegateTest.java:58)
```

(Ohhhh... now I remember why I didn't upgrade to Tycho 1.2 previously — it doesn't propagate the `<trimStackTraces>` ([link](https://bugs.eclipse.org/bugs/show_bug.cgi?id=535881)).  It'll be fixed in Tycho 1.3 which is not yet released.

**Comment by chanseokoh** [comment]
> The Oxygen (4.8) builds

Photon (4.8)

**Comment by briandealwis** [comment]
I don't know what the source of this errorprone logging going into a weird state.  On Java 11 only?  on Travis only?  (or maybe it's javac? `SimpleFileObject` matches a class )

**Comment by briandealwis** [comment]
[Oops!](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/pom.xml#L600):
```xml
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
...
            <configuration>
              <verbose>true</verbose>
```

**Comment by briandealwis** [comment]
I forgot that the cla bot has conniptions.

**Comment by briandealwis** [comment]
It's odd that both the `/push` and `/pr` builds fail for Photon (4.8) on `FlexMavenPackagedProjectStagingDelegateTest#testStage_springBoot()` with an `OperationCanceledException`. Unfortunately the stack traces don't show much as I forgot to revert to Tycho 1.1.  Will fix that now.

```
Running com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest

Importing 1 projects:
    /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.integration.appengine/target/work/data/spring-boot-test/.project

!ENTRY org.eclipse.wst.sse.core 1 1 2018-09-21 16:04:26.188
!MESSAGE Indexing project spring-boot-test for JSP Index Manager
16:04:28.130 [WorkbenchTestable] INFO  o.e.m.i.launch.MavenLaunchDelegate - /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.integration.appengine/target/work/data/spring-boot-test
16:04:28.143 [WorkbenchTestable] INFO  o.e.m.i.launch.MavenLaunchDelegate -  mvn -B package
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.225 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest
testStage_springBoot(com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest)  Time elapsed: 4.224 sec  <<< ERROR!
org.eclipse.core.runtime.OperationCanceledException
	at com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest.testStage_springBoot(FlexMavenPackagedProjectStagingDelegateTest.java:58)
```

Of the 4 timed-out jobs, 12 failed just after having a success build at 47:47.  The other 3 jobs all failed at:
```
913250 [INFO] --- tycho-p2-repository-plugin:1.2.0:assemble-repository (default-assemble-repository) @ google-cloud-plugin-eclipse.repo ---
913251 [INFO] Copying resources from /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/classes to /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/repository
```

That first number is the number of milliseconds since the start and the variance is astonishing:
```
501863 [INFO] Copying resources from /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/classes to /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/repository
```

```
1581130 [INFO] Copying resources from /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/classes to /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/gcp-repo/target/repository
```

**Comment by chanseokoh** [comment]
For the CLA issue, you could branch off of this PR or just a start a fresh new branch with a new PR, if you want.

**Comment by chanseokoh** [comment]
Showing the cause of the error:
```
java.lang.AssertionError: Imported Maven project has errors

/springboot-appengine-standard/pom.xml:9: For artifact {org.springframework.boot:spring-boot-starter-web:null:jar}: The version cannot be empty. (org.apache.maven.plugins:maven-resources-plugin:2.6:resources:default-resources:process-resources)

org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework.boot:spring-boot-starter-web:null:jar}: The version cannot be empty.
```

**Comment by briandealwis** [comment]
Indeed the reference to `org.springframework.boot:spring-boot-starter-web` doesn't have a version.  Weird.
```
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
            <!-- Exclude Tomcat so that it doesn't conflict w/ Jetty server -->
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by chanseokoh** [comment]
Hmm... there's another dependency with no version.

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.121 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.ImportMavenAppEngineStandardProjectTest

runImport(com.google.cloud.tools.eclipse.integration.appengine.ImportMavenAppEngineStandardProjectTest)  Time elapsed: 13.104 sec  <<< FAILURE!

java.lang.AssertionError: Imported Maven project has errors

/springboot-appengine-standard/pom.xml:9: For artifact {org.slf4j:jul-to-slf4j:null:jar}: The version cannot be empty. (org.apache.maven.plugins:maven-resources-plugin:2.6:resources:default-resources:process-resources)

org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.slf4j:jul-to-slf4j:null:jar}: The version cannot be empty.
```

**Comment by briandealwis** [comment]
These versions should be coming from the Spring Boot BOM, but I guess the order matters.
```diff
diff -uwbr 1/springboot-appengine-standard/pom.xml 0/springboot-appengine-standard/pom.xml
--- 1/springboot-appengine-standard/pom.xml	2018-09-13 10:50:04.000000000 -0400
+++ 0/springboot-appengine-standard/pom.xml	2018-09-21 21:26:01.000000000 -0400
@@ -20,6 +20,19 @@
     <maven.compiler.target>${java.version}</maven.compiler.target>
   </properties>
 
+  <dependencyManagement>
+     <dependencies>
+        <dependency>
+            <!-- Import dependency management from Spring Boot -->
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-dependencies</artifactId>
+            <version>${spring.boot.version}</version>
+            <type>pom</type>
+            <scope>import</scope>
+        </dependency>
+    </dependencies>
+  </dependencyManagement>
+
   <dependencies>
     <dependency>
       <groupId>org.springframework.boot</groupId>
@@ -55,19 +68,6 @@
     </dependency>
   </dependencies>
 
-  <dependencyManagement>
-     <dependencies>
-        <dependency>
-            <!-- Import dependency management from Spring Boot -->
-            <groupId>org.springframework.boot</groupId>
-            <artifactId>spring-boot-dependencies</artifactId>
-            <version>${spring.boot.version}</version>
-            <type>pom</type>
-            <scope>import</scope>
-        </dependency>
-    </dependencies>
-  </dependencyManagement>
-
   <build>
     <plugins>
       <plugin>
```

**Comment by chanseokoh** [comment]
Unfortunately, the empty version for `org.springframework.boot:spring-boot-starter-web:null:jar` again.

```
  ImportMavenAppEngineStandardProjectTest.runImport:67 Imported Maven project has errors

/springboot-appengine-standard/pom.xml:9: For artifact {org.springframework.boot:spring-boot-starter-web:null:jar}: The version cannot be empty. (org.apache.maven.plugins:maven-resources-plugin:2.6:testResources:default-testResources:process-test-resources)

org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework.boot:spring-boot-starter-web:null:jar}: The version cannot be empty.
```

**Comment by briandealwis** [comment]
Marking the flakey tests as `@Ignore` for now.

**Comment by chanseokoh** [comment]
Looks good. @briandealwis I need your GitHub approval to merge, as we discussed.

**Pull request merged**
