### PR TITLE
chore: update to Tycho 2.5.0

### PR DESCRIPTION
**Pull request by briandealwis**
Update to Tycho 2.5.0. Note that this PR must be applied after #3668.

### CODE REVIEW

**Comment by briandealwis** [comment]
Oh right, Tycho 2.5 requires Java 11

**Comment by chanseokoh** [comment]
Do we need to update [`toolchains.xml`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/.github/workflows/toolchains.xml)?

**Comment by briandealwis** [comment]
Odd: `ModelRefreshTest#testRejigDeploymentAssembly` is failing:
```
testRejigDeploymentAssembly(com.google.cloud.tools.eclipse.appengine.facets.ui.navigator.model.ModelRefreshTests)  Time elapsed: 5.088 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.google.cloud.tools.eclipse.appengine.facets.ui.navigator.model.ModelRefreshTests.testRejigDeploymentAssembly(ModelRefreshTests.java:314)
```
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/4772848aee0dbc70e2a7e91a4ff2aa9803082738/plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ui/navigator/model/ModelRefreshTests.java#L314

I modified `recordChangedFilesDuring()` to output the changed files, and it shows:
```
changed: [L/test0.7750160131576149/.settings/org.eclipse.wst.common.component]
changed: [L/test0.7750160131576149/.settings/org.eclipse.wst.common.component]
changed: [L/test0.7750160131576149/.settings/org.eclipse.wst.common.component]
changed: [L/test0.7750160131576149/.settings/org.eclipse.wst.common.component, L/test0.7750160131576149/WebContent/WEB-INF/cron.xml, L/test0.7750160131576149/newWebRoot/WEB-INF/dispatch.xml]
```

I need to look at this some more.

**Comment by chanseokoh** [comment]
Also noticed there are other test failures where they shouldn't fail normally.

```
appEngineWebWithNoRuntime(com.google.cloud.tools.eclipse.appengine.standard.java8.ConversionTests)  Time elapsed: 0.014 s  <<< ERROR!
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
	at com.google.cloud.tools.eclipse.test.util.project.TestProjectCreator.getFacetedProject(TestProjectCreator.java:132)
	at com.google.cloud.tools.eclipse.appengine.standard.java8.ConversionTests.appEngineWebWithNoRuntime(ConversionTests.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```java
  public IFacetedProject getFacetedProject() {
    createProjectIfNecessary();
    Preconditions.checkState(facetedProject != null);   // <--- create a project, but it's not faceted?
    return facetedProject;
  }
```

I have no clue.

**Comment by briandealwis** [comment]
Kokoro Windows succeeded!

But 2018-09 failed
```
testImportAppEngineStandardJava7_from1_3_1(com.google.cloud.tools.eclipse.integration.appengine.ImportNativeAppEngineStandardProjectTest)  Time elapsed: 13.523 s  <<< FAILURE!
java.lang.AssertionError: Project does not have AES facet
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.google.cloud.tools.eclipse.integration.appengine.ImportNativeAppEngineStandardProjectTest.testImportAppEngineStandardJava7_from1_3_1(ImportNativeAppEngineStandardProjectTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.eclipse.swtbot.swt.finder.junit.internal.CapturingFrameworkMethod.invokeExplosively(CapturingFrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.runChild(SWTBotJunit4ClassRunner.java:75)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.swtbot.swt.finder.junit.SWTBotJunit4ClassRunner.run(SWTBotJunit4ClassRunner.java:60)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:128)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:46)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:76)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by briandealwis** [comment]
Java 17 seems to be causing a whole host of other problems :-(

**Review by chanseokoh — APPROVED** [review]

**Review by suztomo — APPROVED** [review]

**Pull request merged**
