### PR TITLE
Add M2E SDK feature to required targets

### PR DESCRIPTION
**Pull request by briandealwis**

### CODE REVIEW

**Comment by briandealwis** [comment]
Oops, forgot `oxygen`.

**Comment by elharo** [comment]
Is this a subset or a superset of the m2e feature? Or neither?

**Comment by briandealwis** [comment]
Hmm thanks for asking: I thought it was a superset, since everything resolves fine, but looking at the definition only brings in the `.source` bundles.  The `m2e-wtp` feature brings in most of m2e, but I'll keep the explicit m2e feature to be on the safe side.

**Comment by briandealwis** [comment]
Sorry, missed the `category.xml` @elharo

**Pull request merged**
