### PR TITLE
Update CT4E feature label

### PR DESCRIPTION
**Pull request by chanseokoh**

### CODE REVIEW

**Comment by chanseokoh** [comment]
If we change the feature ID, should we also change the directory name `featues/com.google.cloud.tools.eclipse.suite.e45.feature` to match it?

**Comment by briandealwis** [comment]
+1

**Comment by elharo** [comment]
Should the feature ID really specify an Eclipse version? In hindsight that seems...odd.

**Comment by briandealwis** [comment]
I think we took the oaten from GPE where they had patches/workarounds bugs.  I don't see any reason that we need it.

**Comment by chanseokoh** [comment]
I think it's best for @briandealwis to work on this, which involves modifying `p2.inf`.

**Pull request merged**
