### PR TITLE
Fix JSON structure for Clearcut

### PR DESCRIPTION
**Pull request by chanseokoh**
For some reason that we can't really understand, Clearcut expects that non-primitive fields be wrapped into a singleton array. At least I checked this works.

Also fixed the metadata format. It should be a list of maps, where each map has two keys "key" and "value".

### CODE REVIEW

**Comment by etanshaul** [comment]
@chanseokoh sorry if this is a pain, but do you think you could paste a snippet of a sample json output here? Mainly for IntelliJ's benefit.

**Comment by chanseokoh** [comment]
@etanshaul no problem. Sample output:

```json
[
  {
    "zwieback_cookie": "eda4db4a-c55e-4fc4-817b-62258fa7b8b2",
    "client_info": [
      {
        "desktop_client_info": [
          {
            "os": "Linux"
          }
        ],
        "client_type": "DESKTOP"
      }
    ],
    "log_source_name": "CONCORD",
    "log_event": [
      [
        {
          "sequence_position": 0,
          "event_time_ms": 1557855060445,
          "source_extension_json": "{\"console_type\":\"CLOUD_TOOLS_FOR_ECLIPSE\",\"event_name\":\"appengine.new.project.wizard\",\"event_metadata\":[{\"value\":\"native\",\"key\":\"type\"},{\"value\":\"0.0.0\",\"key\":\"ct4e-version\"},{\"value\":\"4.8.0.v20180611-0500\",\"key\":\"eclipse-version\"}]}"
        }
      ]
    ],
    "request_time_ms": 1557855060445
  }
]
```

`source_extension_json` is a raw string for another embedded JSON. (As a raw string, it doesn't need the extra singleton list.) When unescaped,

```json
{
  "console_type": "CLOUD_TOOLS_FOR_ECLIPSE",
  "event_name": "appengine.new.project.wizard",
  "event_metadata": [
    {
      "value": "native",
      "key": "type"
    },
    {
      "value": "0.0.0",
      "key": "ct4e-version"
    },
    {
      "value": "4.8.0.v20180611-0500",
      "key": "eclipse-version"
    }
  ]
}
```
Seeing that `event_metadata` is not double array, I think the inner JSON parsing doesn't require the additional singleton array unlike `log_event` in the outer JSON.

**Comment by etanshaul** [comment]
regarding the following:
```
"log_event": [
      [
        {
          "sequence_position": 0,
          "event_time_ms": 1557855060445,
          "source_extension_json": "{\"console_type\":\"CLOUD_TOOLS_FOR_ECLIPSE\",\"event_name\":\"appengine.new.project.wizard\",\"event_metadata\":[{\"value\":\"native\",\"key\":\"type\"},{\"value\":\"0.0.0\",\"key\":\"ct4e-version\"},{\"value\":\"4.8.0.v20180611-0500\",\"key\":\"eclipse-version\"}]}"
        }
      ]
    ],
```
Did you find it necessary to doubly wrap the `log_event` array like this?

**Comment by chanseokoh** [comment]
Yeah, consistent with other non-primitive fields. "log_event" is "repeated", meaning an array by itself, i.e., a list of "log events". So it requires the addition wrap over the already array.

**Pull request merged**
