### PR TITLE
Add "test=true" attribute to test bundle "src/"

### LINKED ISSUE #3343: Don't put .classpath in git
So this just happened, again: 

Can we .gitginore .classpath in Git so that rebuilds of target platforms don't do this? Why do we check .classpath into the repo? 

```
elharo-macbookair99:eclipse elharo$ git status
On branch i3340
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.compat.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.facets.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.ui.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebMarkerResolutionGenerator.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ElementProblem.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ObsoleteRuntime.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/VersionQuickAssistProcessor.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFix.java
	modified:   ../plugins/com.google.cloud.tools.eclipse.bugreport.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.googleapis.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.login.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.preferences.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.projectselector.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.sdk.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.sdk.ui.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.ui.status.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.ui.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.usagetracker.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.util.test/.classpath
	modified:   ../plugins/com.google.cloud.tools.eclipse.welcome.test/.classpath
```

### PR DESCRIPTION
**Pull request by chanseokoh**
#3343.

### CODE REVIEW

**Comment by briandealwis** [comment]
Need to check that Oxygen ignores the attribute.

**Comment by chanseokoh** [comment]
Let me quickly check this on Oxygen.

**Comment by chanseokoh** [comment]
I create a tiny project on Oxygen, closed Oxygen, added the attribute on the command line (verified that Oxygen picks up the changes), opened Oxygen, and found no problem. A small main class runs OK.

And even if it had a problem, this is for CT4E developers, so I think we're good.

**Comment by chanseokoh** [comment]
Oh, and Oxygen did not remove the attribute.

**Pull request merged**
