### PR TITLE
I2232 dataflow hierarchy async issue

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes [this problem](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2232#issuecomment-322883716) in #2232.

- Sets `hierarchy` to null while it is being updated by the async job (launched by `updateHierarchy()`).
- Make readers of `hierarchy` do proper things if `hierarchy` is null.
   - One of the readers is another UI-updating async job (launched by `updatePipelineOptionsForm()`). 

There is some complication because of the two async jobs, one (UI-updating job) depending on the other (`hierarchy`-updating job).

### CODE REVIEW

**Comment by chanseokoh** [comment]
I need some more thoughts. Closing until ready.

**Comment by chanseokoh** [comment]
This should be good. Ready for review.

**Comment by chanseokoh** [comment]
Although this PR fixes [this problem](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2232#issuecomment-322883716), @briandealwis may have a more grand plan which can tackle #2289 together. @briandealwis I expect you to take this PR and the issues from now on. It's up to you if you'll work on top of this PR or close it. (Thanks!)

**Comment by briandealwis** [comment]
Fixes by blocking the UI with ModalContext/IRunnableWithContext in #2326

**Pull request closed without merging**
