### PR TITLE
Log debug info for #1897

### PR DESCRIPTION
**Pull request by chanseokoh**
For #1897. `SWTBotTreeItem.toString()` will do the job.

### CODE REVIEW

**Comment by chanseokoh** [comment]
This is funny. The Kokoro failure of this PR triggered #1897 (very opportunistic), but there was no debug info logged by this PR. This doesn't make sense, so I'm a bit perplexed.

**Comment by chanseokoh** [comment]
Ah, okay, the log was quite a bit more above the assertion failure message:
```
INFO: submitting command: C:\Program Files\Java\jdk1.8.0_131\bin\java.exe -Xdebug -Xrunjdwp:transport=dt_socket,server=n,suspend=y,quiet=y,address=52119 -javaagent:C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\agent\appengine-agent.jar -Dappengine.sdk.root=C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java -cp C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --address=localhost --port=8080 --allow_remote_shutdown --disable_update_check T:\src\github\google-cloud-eclipse\plugins\com.google.cloud.tools.eclipse.integration.appengine\target\work\data\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\testapp
    [GitHub #1897 debug info] TreeItem with text {}
12:45:19.861 [main] WARN  o.e.s.s.finder.widgets.SWTBotButton - Widget is not enabled: (of type 'Button' and with mnemonic 'OK' and with style 'SWT.PUSH')
```
There certainly exists a tree item, but it's text is empty. Maybe a race condition: we wait until there becomes one tree item, but we check its text too early before the UI thread sets a proper text.

**Comment by briandealwis** [comment]
There may have been an execution error with launching devappserver.  As part of trying to diagnose the very strange test problems I encountered in #1529, I had [added some support to the tests to dump the console output from launching the devappserver](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1529/files#diff-389b5df3ae52f2bf1d8d52e9bb75eda9R134).

(I never did get to the bottom of #1529)

**Comment by chanseokoh** [comment]
@briandealwis That's very interesting.

Before that, what seems weird though is that the test calls `SwtBotTreeUtilities.waitUntilTreeHasText(bot, allItems[0])`, which is supposed to wait until `allItems[0]` has a non-empty text. However, it end up seeing an empty text, so I think the method is either not functioning properly or timing out.

**Comment by briandealwis** [comment]
> or timing out

As might happen if the [launched JVM never actually ran for some reason](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1529#issuecomment-285582559)…

**Comment by briandealwis** [comment]
I wonder if `ProjectUtils#waitForProjects()` shouldn't instead forcibly trigger a rebuild via `IWorkspace#build()` rather than wait for the auto build job.

**Comment by chanseokoh** [comment]
Hopefully #1897 is fixed by #2047. Closing.

**Pull request closed without merging**
