### PR TITLE
Cannot install CT4E if GPE is already installed and vice versa

### PR DESCRIPTION
**Pull request by nbashirbello**
Fix for #866

### CODE REVIEW

**Comment by nbashirbello** [comment]
Not ready for review.

**Comment by nbashirbello** [comment]
Ready for review

**Comment by nbashirbello** [comment]
In GPE, we would have to add a notification that will be displayed on start-up that the GPE plugin has been replaced with CT4E (listing the features CT4E has and doesn't have). Users would be able to mute the notification permanently.

**Comment by briandealwis** [comment]
GPE has some notification system — I remember seeing something when there was a new update. We might be able to leverage that.

**Pull request merged**
