### PR TITLE
Fixes the URL for Objectify javadoc

### PR DESCRIPTION
**Pull request by akerekes**
It will still not work because of #932 , but once javadoc.io maintainers change the CloudFlare settings, it will.

### CODE REVIEW

**Comment by akerekes** [comment]
@chanseokoh that's OK, if you request for a specific resource, then it works, check with this: http://static.javadoc.io/com.googlecode.objectify/objectify/5.1.13/com/googlecode/objectify/ObjectifyFactory.html

**Comment by briandealwis** [comment]
@chanseokoh you should have no problems if you launch with `-Dhttp.agent=random/1.0` or anything other than `Java/1.XXXX`.

**Comment by akerekes** [comment]
@briandealwis The root directory will give error even in a browser.

**Comment by briandealwis** [comment]
I wasn't sure if @chanseokoh was referring to the javadocUri base URL or from the actual Javadoc hover as they haven't fixed that.  They both return _Access Denied_ but with very different content.

**Pull request merged**
