### PR TITLE
Load .java8 bundle in .validation.test / ignore failing tests blocked by another bug

### LINKED ISSUE #2049: False positives in tests: XmlSourceValidatorTest.testValidate() and WebXmlValidatorTest.testValidateJavaServlet()
As it has been, the test succeeds on Travis and locally. However, when running inside Eclipse as a JUnit plug-in test, it fails. It may have something to do with the fact that `mvn verify` doesn't load all bundles that are available when running tests in Eclipse.

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #2049.

In order for these two tests in `.validation.test` to work properly, we need to load the `.java8` bundle, because the `.java8` bundle additionally defines constraints between Servlet versions and Java versions.

However, because the bug in defining the constraints in `.java8` (#2044), loading the `.java8` bundle will make these tests correctly fail. Until #2044 is fixed, we need to `@Ignore` them. I made a comment in #2044 to remove these `@Ignore` annotations when fixing #2044.

### CODE REVIEW

**Comment by chanseokoh** [comment]
@braindealwis may have some restructuring idea to fix #2044. @braindealwis what do you think? This is blocking #2048.

**Comment by briandealwis** [comment]
I was holding off on this, hoping that I could make it obsolete with #2044 and friends. As that will take longer…

That said: wouldn't it be better to use `Assume` in the test rather than ignore the tests completely?

**Comment by chanseokoh** [comment]
Not immediately clear how we could express the `Assume`. The end state of these tests seems to depend highly on the outcome of #2044, as these tests are asking "is it a conflict to specify 3.1 in `web.xml` if the project has an App Engine Standard facet"?

**Comment by briandealwis** [comment]
Something like:
```java
    Assume.assumeTrue("Cannot be run with Java 8 support",
        AppEngineStandardFacet.FACET_VERSION.conflictsWith(JavaFacet.VERSION_1_8));
```

and

```java
    Assume.assumeTrue("Cannot be run with Java 8 support",
        AppEngineStandardFacet.FACET_VERSION.conflictsWith(WebFacetUtils.WEB_31));
```

**Comment by chanseokoh** [comment]
Changed to use `Assume()`. However, when fixing #2044, these tests should be fixed together so that they run meaningful tests.

**Pull request merged**
