### PR TITLE
Attempt to fix Oxygen builds

### PR DESCRIPTION
**Pull request by briandealwis**
For #1345

### CODE REVIEW

**Comment by chanseokoh** [comment]
For this PR, the oxygen build failed on `AppEngineStandardProjectConvertCommandHandlerTest`, which uses `TestProjectCreator`. In relation to https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1340#issuecomment-277716681, and knowing that the offending test in this PR doesn't use `NonSystemJobScheduleListener`, I wonder if `TestProjectCreator` increases the changes of timeouts in Oxygen.

**Comment by briandealwis** [comment]
On my docker simulation, I see tests failing with:
```
com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest  Time elapsed: 0.267 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: There is no active view
	at org.eclipse.swtbot.eclipse.finder.SWTWorkbenchBot.activeView(SWTWorkbenchBot.java:203)
	at com.google.cloud.tools.eclipse.swtbot.SwtBotWorkbenchActions.closeWelcome(SwtBotWorkbenchActions.java:177)
	at com.google.cloud.tools.eclipse.integration.appengine.BaseProjectTest.setUp(BaseProjectTest.java:44)
```

**Comment by briandealwis** [comment]
Dropping the `while(!isIdle())` leads to deletion-related errors popping up again:
```
!ENTRY org.eclipse.wst.common.project.facet.core 4 0 2017-02-06 16:45:36.185
!MESSAGE Cannot modify a deleted project.
!ENTRY org.eclipse.wst.validation 4 0 2017-02-06 16:45:36.230
!MESSAGE IWAE0027E Could not retrieve the validation configuration for resource testproject0.8107205146211439.
!STACK 0
java.lang.reflect.InvocationTargetException: IWAE0027E Could not retrieve the validation configuration for resource testproject0.8107205146211439.
	at org.eclipse.wst.validation.internal.ConfigurationManager.getProjectConfiguration(ConfigurationManager.java:135)
```

**Comment by briandealwis** [comment]
It looks like our SWTBot 10s timeout is too small, as I saw `DebugNativeAppEngineStandardProjectTest` timeout while I watched it waiting for the server to launch.
```
testDebugLaunch(com.google.cloud.tools.eclipse.integration.appengine.DebugNativeAppEngineStandardProjectTest)  Time elapsed: 73.985 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: Text not found!
```

**Comment by briandealwis** [comment]
Committed the alternative in #1348

**Pull request closed without merging**
