### PR TITLE
Add new project wizard extensions

### PR DESCRIPTION
**Pull request by briandealwis**
Adds the native and maven projects to the _New_ menu.  Note that, you'll need to reset your perspective to pick up these changes if you're running from an existing workspace/window.

screen shot 2016-12-08 at 4 22 00 pm
.

### CODE REVIEW

**Comment by briandealwis** [comment]
This adds the extension to all perspectives. It might be better to add it to the _Java_, _Java EE_, and _Web_ perspectives.

**Comment by chanseokoh** [comment]
Good to know how to add these. Will these available in any perspective? Lastly, one concern of mine is, we may end up adding too many wizards, e.g., flex env, Gradle-based, etc.

BTW, the XML has some Git stash markers.

**Comment by briandealwis** [comment]
Oh geesh. Github needs a :blush: reaction.

**Comment by branflake2267** [comment]
Couple random notes from a random user's angle. 

* It might be a bit greedy to be in all perspectives. For instance, as a Java user, I'm in the Java perspective most of the time and I think it's one of those features that isn't obscure to Eclipse users. 

* Regarding labeling. I might suggest something like moving Maven next to Java, instead of Maven based. Or better yet, only use one shortcut and then specify in the dialog specify which build type. I like it either way, but looking into the future, if you add more build types might get busy. 
 - Google App Engine Standard Java Project
 - Google App Engine Standard Java Maven Project
 - [Google App Engine Standard Java Gradle|Ant|Blaze Project]

**Comment by briandealwis** [comment]
Restricted the set of perspectives extended.  

Opened #1094 to consider new project wizard naming.

**Comment by briandealwis** [comment]
Fixes #1080

**Pull request merged**
