### PR TITLE
Guava 21

### PR DESCRIPTION
**Pull request by elharo**
which requires appengine-plugins-core 0.5.0
which changed some method signatures

### CODE REVIEW

**Comment by briandealwis** [comment]
There are still a bunch of `Import-Package` from `com.google.cloud.tools.appengine.*` which are at version 0.4.4.

**Comment by elharo** [comment]
```
[INFO] --- tycho-p2-repository-plugin:1.1.0:assemble-repository (default-assemble-repository) @ ide-target-platform.repo ---
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to org.apache.commons.compress [1.6.0.v201310281400].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.google.guava [21.0.0].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.fasterxml.jackson.core.jackson-core [2.6.2.v20161117-2150].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to org.apache.commons.compress [1.6.0.v201310281400].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.google.guava [21.0.0].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.fasterxml.jackson.core.jackson-core [2.6.2.v20161117-2150].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to org.apache.commons.compress [1.6.0.v201310281400].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.google.guava [21.0.0].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.fasterxml.jackson.core.jackson-core [2.6.2.v20161117-2150].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to org.apache.commons.compress [1.6.0.v201310281400].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.google.guava [21.0.0].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.fasterxml.jackson.core.jackson-core [2.6.2.v20161117-2150].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to org.apache.commons.compress [1.6.0.v201310281400].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.google.guava [21.0.0].; Unable to satisfy dependency from 201802281508.Default 1.0.0.A2DQEZUcM0Z--Efyz-GEnQfAz0cmPmM-LvOyW to com.fasterxml.jackson.core.jackson-core [2.6.2.v20161117-2150].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
```

**Comment by chanseokoh** [comment]
Oh, great. Kokoro may have technical problems now.

**Comment by briandealwis** [comment]
Those warnings are similar to the `com.google.gson` warnings we saw in #2680.  In that case, it was because we were pulling in `com.google.gson` 2.7.0, whereas WTP wanted `com.google.gson` 2.8.2.

These warnings are because of the Docker Tools (`org.eclipse.linuxtools.docker`).  I didn't fully remove the Docker Tools in #2860; I just removed the reference to in `gcp-repo`.

But the Docker Tools, or rather its dependency `com.spotify.docker.client`, has dependencies on packages:
  - `org.apache.commons.compress.*` version 1.6.0
  - `com.fasterxml.jackson.*` 2.6.2.
  - `com.google.common.*` version 18

But our pom.xml pulls in `org.apache.commons.compress` 1.14, `com.fasterxml.jackson.core.jackson-core` 2.8.6, and (now) `com.google.guava` 21.0.

The referenced wiki page talks of this being a problem with feature patches.  And the release train repositories (e.g., `download.eclipse.org/releases/oxygen`) do have a feature patch (from ObjectTeams).

**Comment by briandealwis** [comment]
Ah, yes: ObjectTeams patches the `org.eclipse.jdt` feature to replace the `org.eclipse.jdt.core` bundle.

**Pull request merged**
