### PR TITLE
turn on dataflow

### PR DESCRIPTION
**Pull request by elharo**
@tgroh @briandealwis I'd like to soft launch this (no fanfare) early next week.

### CODE REVIEW

**Comment by tgroh** [comment]
What's left to do to make this soft-launch happen?

**Comment by elharo** [comment]
We need to get login working at a minimum. I'd also like to fix some of the recent bugs @chanseokoh has found.

**Comment by briandealwis** [comment]
Do we want to be able to install Dataflow separately from the rest of CT4E?  Should we have a separate feature that pulls in the minimal core?

(Or do we wait and see if people ask.)

**Comment by elharo** [comment]
Login should work now.

**Pull request merged**
