### PR TITLE
Use App Engine 64 icon instead of GCP 32

### LINKED ISSUE #84: Use proper icons for GCP resources
Use App Engine icon for local dev server in the Eclipse UI.
Also we can add icons for GCE,GKE for future usage.

### PR DESCRIPTION
**Pull request by elharo**
@briandealwis @nbashirbello @arouzrokh fix #84

### CODE REVIEW

**Comment by briandealwis** [comment]
Can you add a `gae-16x16@2x.png` too?  It will be automatically picked up on HiDPI.

**Comment by elharo** [comment]
Is that somehow different than a gae-32x32.png? I.e. is it a gae-32x32.png with the different file name?

**Comment by briandealwis** [comment]
Yep, the 32x32 image would be fine.  The file name mapping is handled internally and we can't influence it.

**Comment by briandealwis** [comment]
@arouzrokh I found a [1600x1400 App Engine icon](https://lh5.googleusercontent.com/C-2aV2ARcAndc_empiXzsKfa77DJgexrDxt1UEoXQuFj6IN88FJ43Wr97XnBvJUmFxOCQAEAP2GKIayiZHG4YGWSrJ9VilGlnQeswWtgvINCx842WMUiKDbHaKwpdzqUFw) online, though I'm unsure where it's linked to.  With it, I get a nicer-looking 16x16 icon with more definition in the tail and wings:

app-engine-16x16

vs the image used here:

embedded image

**Comment by elharo** [comment]
added 2x icon

**Comment by briandealwis** [comment]
Ugh that's a ghastly 32x32 image!
included image

Here's the one I generated from that 1600x1400 image:
app-engine-32x32

We can improve them separately.

**Pull request merged**
